version: '3.8'

services:
  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    ports:
      - "9042:9042"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    mem_limit: 2g

  janusgraph:
    image: janusgraph/janusgraph:latest
    container_name: janusgraph
    depends_on:
      - cassandra
      - elasticsearch
    ports:
      - "8182:8182"
    environment:
      - gremlin.graph=org.janusgraph.core.ConfiguredGraphFactory
      - storage.backend=cql
      - storage.hostname=cassandra
      - index.search.backend=elasticsearch
      - index.search.hostname=elasticsearch

  gremlin-visualiser:
    image: prabushitha/gremlin-visualiser
    container_name: gremlin-visualiser
    ports:
      - "3000:3000"
    environment:
      - GREMLIN_SERVER_URL=ws://janusgraph:8182/gremlin
